### ISSUE TITLE
Access Denied

### ISSUE THREAD

**Issue by sergiobr** [tty02-fl/coinmate.io-api#1]
Hello,
I suspect that it is not about yout implementation because I had tried other languages and even in the apiary tests I receive the "Access Denied" message.
Any one is experiencing this problem also or maybe I'm missing anything?

I appreciate a lot if someone can help.

Thank you

**Comment by tty02-fl** [comment]
Verify that your credentials are correct and your account can use the API. 
https://coinmate.io/pages/secured/accountAPI.page
